title: 'Captivated'
author: 'Emily K Anderson'
description: 'Captivated Customer website'
baseurl: "/"
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','vendor']
include: ['_pages']
source:      _build
destination: _site
