title: 'Captivated'
author: 'Emily K Anderson'
description: 'Captivated enables customers to communicate with your business through text messaging. Learn how to easily manage conversations with your customers via mobile texting.'
# url: &url 'http://localhost:3000'
url: &url 'http://captivated.works'
baseurl: &baseurl '/'
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','vendor']
include: ['_pages']
source:      _build
destination: _site


# main navitation items
navigation:
  - title: Home
    url: *baseurl
    id: home
  - title: How it works
    url: /product/how-it-works/
    id: how-it-works
  - title: Features
    url: /product/features/
    id: features
  - title: Markets
    url: /product/markets/
    id: markets
  - title: Blog
    url: blog/
  - title: FAQ
    url: faq/
    id: faq
  - title: Contact
    url: contact/
    id: contact

# main call to action items
maincta:
  - title: Log In
    url: http://app.captivated.works/
  - title: Sign Up
    url: get-started/

# main call to action items
mainctadesktop:
  - title: <i class="material-icons">help_outline</i> FAQ
    url: faq/
    id: faq
  - title: Log In
    url: http://app.captivated.works/
  - title: Sign Up
    url: get-started/


# lower footer nav
lowerfootnav:
  # - title: Brand Style Guide
  #   url: style-guide/
  - title: Privacy Policy
    url: privacy-policy/
  - title: Terms & Conditions
    url: terms-conditions/
